global: {}
argocd-config:
  repoUrl: "http://gogs.tools:3000/toolkit/gitops.git"
  project: "openshift-gitops"
  applicationTargets:
  - targetRevision: master
    createNamespace: false
    targetNamespace: "uat-deploy"
    applications:
     - name: "spm"
       path: "qa/spmeight-argocd/spm"
       type: helm
     